import { Component, Input } from '@angular/core';
import { TopicService } from '../services/topic.service';
import { AuthService } from '../services/auth.service';
import { Post } from '../models/post.model';

@Component({
  templateUrl: './post-from.component.html',
  styleUrl: './post-from.component.css'
})
export class PostFromComponent {

  @Input() topicId: number = 0;
  title: string = '';
  content: string = '';

  constructor(
    private topicService: TopicService,
    private authService: AuthService
  ) {}
  
  submitPost(): void {
    if (this.title.trim() && this.content.trim()) {
      const currentUser = this.authService.getCurrentUser();
      if (currentUser) {
        const newPost: Post = {
          id: 0, // Set to 0 since it will be generated by the server
          title: this.title,
          content: this.content,
          authorId: currentUser.id,
          topicId: this.topicId
        };
        this.topicService.createPost(newPost)
          .subscribe(post => {
            // Redirect or do something else upon successful post creation
            console.log('Post created:', post);
          });
      }
    }
  }
}


